//app.module('how2all');
//app.controller('ExploreCtrl', ['$scope', function($scope){
//$scope.guides = [
//	{"_id":"45vC6hxZCh2zxGNs9","difficulty":"0","free":true,"fullDescription":"lkdjfslkdfjsl;kdfja;skdjf;skdfj;asdfasd","mainTag":"FREE TIME AND FUN","owner":"wghzyRzKDLrwLCN8w","public":true,"rating":{"ratingAvg":"3"},"requirements":["ertewgdsfg","sdfg"],"skills":["erterter","tert"],"tags":["tterte","dfs"],"title":"jhkjhjkhlkjhkj"},
//	{"_id":"5LkzFsdzPizx3Ssmp","difficulty":"0","free":true,"fullDescription":"ow to cut string or rope if you haven't got a knife or a pair of scissors. Great life hack trick to help you in an emergency. Cut rope with string!","mainTag":"TIPS","owner":"wghzyRzKDLrwLCN8w","public":true,"rating":{"ratingAvg":"1.5"},"requirements":[],"skills":[],"tags":["Cut","Rope","Emergency","string"],"title":"How to Cut Rope in an Emergency"},
//	{"_id":"NGmyMMoceZoELzHzP","difficulty":"1","free":true,"fullDescription":"How to prepare and serve a pineapple. With just a few cuts your pineapple will impress your friends and be perfect for serving at a party. Fun and simple food trick.\naviram h'a gever!","mainTag":"KITCHEN AND RECEPIES","owner":"wghzyRzKDLrwLCN8w","public":true,"rating":{"ratingAvg":"3.5"},"requirements":["A sharp knife","Cutting board"],"skills":["No special skills are required"],"tags":["Serve","Pineapple"],"title":"How to Serve Pineapple"},
//	{"_id":"dCw8ikoE4RuNLmuSc","fullDescription":"oijiopi[oiuy8ui9opoyuiopl;[oiuuijokpl;['ojhjikol;","mainTag":"MUSIC AND INSTRUMENT","owner":"wghzyRzKDLrwLCN8w","public":true,"requirements":[],"skills":[],"tags":["okpok","ii-p[","ij0okp["],"title":"0oi0o"},
//	{"_id":"fuECamCWqwNWLs6Qw","difficulty":"2","free":true,"fullDescription":"Draw 3D objects using lines on paper. Make objects appear to be coming out of the page using this simple technique. Great fun to do with children. Draw a three dimensional hand, spoon and Bart Simpson!","mainTag":"ART","owner":"wghzyRzKDLrwLCN8w","public":true,"rating":{"ratingAvg":"3"},"requirements":["Pencil","Blank page"],"skills":["Basic drawing skills"],"tags":["draw","3D"],"title":"how to draw"}
//];
//
//}]);